// Generated by CoffeeScript 1.6.3
(function() {
  angular.module('chosenExampleApp', ['localytics.directives']).controller('IndexCtrl', [
    '$scope', '$q', '$timeout', function($scope, $q, $timeout) {
      var simulateAjax;
      simulateAjax = function(result) {
        var deferred, fn;
        deferred = $q.defer();
        fn = function() {
          return deferred.resolve(result);
        };
        $timeout(fn, 3000);
        return deferred.promise;
      };
      $scope.optionsFromQuery = (function() {
        var result;
        result = ['grooo', 'wowowowow', 'lakakalakakl', 'yadayada', 'insight', 'delve', 'synergy'];
        return simulateAjax(result);
      })();
      $scope.optionsFromQueryAsHash = (function() {
        var result;
        result = {
          win: "Brilliant Escape",
          fail: "Untimely Demise"
        };
        return simulateAjax(result);
      })();
      $scope.emptyOptions = (function() {
        return simulateAjax([]);
      })();
      $scope.directiveOptions = {
        no_results_text: "SO SORRY"
      };
      $scope.myPets = ['cat'];
      $scope.pets = {
        cat: 'Cat',
        dog: 'Dog',
        hamster: 'Hamster'
      };
      $timeout(function() {
        return $scope.$apply(function() {
          return $scope.myPets.push('hamster');
        });
      }, 1000);
      return $scope.disabled = true;
    }
  ]);

}).call(this);
