// Generated by CoffeeScript 1.6.2
(function() {
  angular.module('chosenExampleApp', ['localytics.directives']).controller('IndexCtrl', [
    '$scope', '$q', '$timeout', function($scope, $q, $timeout) {
      var simulateAjax;

      simulateAjax = function(result) {
        var deferred, fn;

        deferred = $q.defer();
        fn = function() {
          return deferred.resolve(result);
        };
        $timeout(fn, 3000);
        return deferred.promise;
      };
      $scope.optionsFromQuery = (function() {
        var result;

        result = ['grooo', 'wowowowow', 'lakakalakakl', 'yadayada', 'insight', 'delve', 'synergy'];
        return simulateAjax(result);
      })();
      $scope.emptyOptions = (function() {
        return simulateAjax([]);
      })();
      return $scope.directiveOptions = {
        no_results_text: "SO SORRY"
      };
    }
  ]);

}).call(this);
